kind: pipeline
type: docker
name: default

clone:
  default:
    image: plugins/git
    skip_verify: true

workspace:
  base: /drone/go
  path: src/github.com/skhut/go_web_templating

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test